services:
  app:
    build:
      # Use the current directory as build context and build only up to the 'base' stage (for development mode)
      context: '.'
      target: 'base'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    env_file:
      - ./.env.local
    command: 'npm run dev'

volumes:
  node_modules_volume:
